{{- $a := .Values.apiConsumers -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apicon.name" . }}
  namespace: {{ include "apicon.ns" . }}
  labels:
    {{- include "apicon.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  selector:
    {{- include "apicon.selector" . | nindent 4 }}
  ports:
    - {name: http, port: {{ $a.service.port }}, targetPort: http}
{{- if $a.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "apicon.name" . }}
  namespace: {{ include "apicon.ns" . }}
  labels:
    {{- include "apicon.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  host: {{ include "apicon.routeHost" . }}
  to: {kind: Service, name: {{ include "apicon.name" . }}}
  port: {targetPort: http}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
